services:
  scraper:
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - "0.0.0.0:8080:8080"
    shm_size: "1gb"
    volumes:
      - ./sessions:/sessions
    init: true

  browser-login:
    build:
      context: .
      dockerfile: Dockerfile.visual
    profiles: ["login"]
    shm_size: "2gb"
    ports:
      - "127.0.0.1:6080:6080"
    volumes:
      - ./sessions:/sessions
    init: true
